tap "homebrew/bundle"
tap "homebrew/cask-fonts"

# Formulas
brew "awscli"
brew "git"
brew "gh"
brew "neovim"
brew "node"
brew "ripgrep"
brew "tmux"
brew "colima"
brew "docker"
brew "docker-compose"
brew "docker-buildx"
brew "docker"
brew "fzf"
brew "fd"
brew "bat"
brew "aria"

# Casks 
cask "iterm2"
