tap "homebrew/bundle"
tap "homebrew/cask-fonts"

# Formulas
brew "awscli"
brew "git"
brew "neovim"
brew "node"
brew "ripgrep"
brew "tmux"
brew "colima"
brew "docker"
brew "docker-compose"
brew "docker-buildx"
brew "docker"
brew "fzf"

# LSPs
brew "lua_language_server"
brew "typescript_language_server"
brew "pyright"

# Casks 
cask "iterm2"
