tap "homebrew/bundle"
tap "homebrew/cask-fonts"

# Formulas
brew "awscli"
brew "git"
brew "gh"
brew "neovim"
brew "node"
brew "ripgrep"
brew "tmux"
brew "colima"
brew "docker"
brew "docker-compose"
brew "docker-buildx"
brew "docker"
brew "fzf"
brew "fd"
brew "bat"
brew "aria"

# LSPs
brew "lua_language_server"
brew "typescript_language_server"
brew "basedpyright" # forked version of pyright, better supported (no telemetry)
brew "vscode-langservers-extracted" # includes jsonls, html, cssls, eslint

# Casks 
cask "iterm2"
cask "love2d"
