set-option -sa terminal-overrides ",xterm*:Tc"

set -g mouse on
bind-key -n MouseDown1Status select-window -t=

# Set prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Source tmux configs
bind R source-file ~/.config/tmux/tmux.conf

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R

bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# tmux popup buffers
bind t popup -w 80% -h 45% -E "TMUX_POPUP=1 zsh"

# Overrides confirmation prompt when killing pane
bind-key x kill-pane

# List of plugins
set -g @plugin "tmux-plugins/tpm"

set -g allow-rename off

# Sets the terminal title to use the window title
set-option -g set-titles on
set-option -g set-titles-string "#S / #W"

# General settings pulled from tmux-sensible
set -s escape-time 0 
set -g history-limit 50000
set -g display-time 4000
set -g status-interval 5
set -g focus-events on # Focus events for vim/neovim
setw -g aggressive-resize on  # Better multi-monitor support

# Status bar
set -g status-position bottom
set -g status-justify left

set -g status-style bg=default

set -g status-left-length 99 
set -g status-right-length 99

set -g status-left "#[fg=#181826,bg=#89b4fa,bold] #S/#W #[default]" #89b4fa - blue
set -g status-right ""

# Window list
setw -g window-status-format " #I "
setw -g window-status-current-format "#[fg=#181825,bg=#a6e3a2,bold] #I #[default]" #a6e3a2 - green

# Enable vim keybinds in copy/choose mode
setw -g mode-keys vi
# Set highlighting and yanking to use vim keybinds
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel

set -g status-justify absolute-centre

# Set status bar background
set -g @default_style "set -g status-style bg=default,fg=white; set -g message-style bg=default,fg=white; set -g message-command-style bg=default,fg=white"
# Updates bg depending on if nvim is active in window/pane
set -g @flex_style 'if-shell "[ #{pane_current_command} = nvim ]" \
  "set -g status-style bg=#24273a,fg=white; set -g message-style bg=#24273a,fg=white; set -g message-command-style bg=#24273a,fg=white" \
  "set -g status-style bg=default,fg=white; set -g message-style bg=default,fg=white; set -g message-command-style bg=default,fg=white"'

set-hook -g after-new-window 'run-shell -C "#{@flex_style}"'
set-hook -g after-select-window 'run-shell -C "#{@flex_style}"'
set-hook -g client-session-changed 'run-shell -C "#{@flex_style}"'
set-hook -g window-unlinked 'run-shell -C "#{@flex_style}"'
set-hook -g pane-mode-changed 'if-shell -F "#{!=:#{pane_mode},tree-mode}" "run-shell -C \"#{@flex_style}\""'

# Wrap the Window tree view with conditional exit logic
bind w run-shell -C "#{@default_style}" \; choose-tree -Zw
bind s run-shell -C "#{@default_style}" \; choose-tree -Zs


run '~/.config/tmux/plugins/tpm/tpm'
