
set-option -sa terminal-overrides ",xterm*:Tc"

set -g mouse on
bind-key -n MouseDown1Status select-window -t=

# Set prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Source tmux configs
bind R source-file ~/.config/tmux/tmux.conf

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R

bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# tmux popup buffers
bind t popup -w 80% -h 85% -E "zsh"

# Overrides confirmation prompt when killing pane
bind-key x kill-pane

# List of plugins
set -g @plugin "tmux-plugins/tpm"

set -g allow-rename off

# Sets the terminal title to use the window title
set-option -g set-titles on
set-option -g set-titles-string "#S / #W"

# General settings pulled from tmux-sensible
set -s escape-time 0 
set -g history-limit 50000
set -g display-time 4000
set -g status-interval 5
set -g focus-events on        # focus events for vim/neovim
setw -g aggressive-resize on  # better multi-monitor support

# Status bar
set -g status-position bottom
set -g status-justify left

set -g status-style bg=default

set -g status-left-length 99 
set -g status-right-length 99

set -g status-left ""
set -g status-right ""

# Window list
setw -g window-status-format " #I "
setw -g window-status-current-format "#[fg=black,bg=green,bold] #I #[default]"

# Enable vim keybinds in copy/choose mode
setw -g mode-keys vi
# Set highlighting and yanking to use vim keybinds
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel

set -g status-justify centre

# TODO: Refactor this so the status bar background is more consistant
# Set status bar background
set-hook -g after-select-window '
if-shell "[ \"#{pane_current_command}\" = \"nvim\" ]" \
"set -g status-style bg=#24273a,fg=white; \
 set -g message-style bg=#24273a,fg=white; \
 set -g message-command-style bg=#24273a,fg=white" \
"set -g status-style bg=default,fg=white; \
 set -g message-style bg=default,fg=white; \
 set -g message-command-style bg=default,fg=white"
'
set-hook -g after-new-window '
if-shell "[ \"#{pane_current_command}\" = \"nvim\" ]" \
"set -g status-style bg=#24273a,fg=white; \
 set -g message-style bg=#24273a,fg=white; \
 set -g message-command-style bg=#24273a,fg=white" \
"set -g status-style bg=default,fg=white; \
 set -g message-style bg=default,fg=white; \
 set -g message-command-style bg=default,fg=white"
'
set-hook -g window-unlinked '
if-shell "[ \"#{pane_current_command}\" = \"nvim\" ]" \
"set -g status-style bg=#24273a,fg=white; \
 set -g message-style bg=#24273a,fg=white; \
 set -g message-command-style bg=#24273a,fg=white" \
"set -g status-style bg=default,fg=white; \
 set -g message-style bg=default,fg=white; \
 set -g message-command-style bg=default,fg=white"
'
set-hook -g client-session-changed '
if-shell "[ \"#{pane_current_command}\" = \"nvim\" ]" \
"set -g status-style bg=#24273a,fg=white; \
 set -g message-style bg=#24273a,fg=white; \
 set -g message-command-style bg=#24273a,fg=white" \
"set -g status-style bg=default,fg=white; \
 set -g message-style bg=default,fg=white; \
 set -g message-command-style bg=default,fg=white"
'

# Wrap the Window tree view with conditional exit logic
bind w run-shell 'tmux set -g status-style "bg=default,fg=white" ; tmux set -g message-style "bg=default,fg=white" ; tmux set -g message-command-style "bg=default,fg=white"' \; choose-tree -Zw

# Wrap the Session tree view with conditional exit logic
bind s run-shell 'tmux set -g status-style "bg=default,fg=white" ; tmux set -g message-style "bg=default,fg=white" ; tmux set -g message-command-style "bg=default,fg=white"' \; choose-tree -Zs

run '~/.config/tmux/plugins/tpm/tpm'
